---
# tasks file for gitlab-user-training-repos

- name: Importing training repository for each user
  gitlab_project:
    server_url: "http://{{ hostvars[groups['worker_node'][0]]['ansible_ssh_host'] }}:30180"
    validate_certs: False
    login_user: root
    login_password: "{{ gitlab_root_password }}"
    name: "{{ gitlab_training_repository_name }}"
    issues_enabled: False
    wiki_enabled: False
    snippets_enabled: False
    import_url: "{{ gitlab_training_repository_source }}"
    state: present
  delegate_to: localhost
  loop: "{{ training_users }}"

- name: Add push webook for each of the training repositories
  gitlab_hooks:
    api_url: "http://{{ hostvars[groups['worker_node'][0]]['ansible_ssh_host'] }}:30180/api"
    enable_ssl_verification: False
    login_user: root
    login_password: "{{ gitlab_root_password }}"
    project: "{{ item }}/{{ gitlab_training_repository_name }}"
    hook_url: "http://postb.in/quEdKPjA"
    #hook_url: "https://{{ item }}.{{ training_base_url }}/jenkins/funwave-build?token=12345"
    state: present
  delegate_to: localhost
  loop: "{{ training_users }}"
