---

- name: restart gitlab
  command: docker-compose up -d --force-recreate gitlab
  args:
    chdir: "{{ gitlab_deploy_dir }}"
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when

- name: restart gitlab traefik
  command: docker-compose up -d --force-recreate traefik
  args:
    chdir: "{{ gitlab_deploy_dir }}"
  register: gitlab_restart_traefik
  failed_when: gitlab_restart_traefik_handler_failed_when

- name: recreate gitlab stack
  command: docker-compose up -d --force-recreate
  args:
    chdir: "{{ gitlab_deploy_dir }}"
  register: gitlab_recreate_stack
  failed_when: gitlab_recreate_stack_handler_failed_when