---

# Specified version because of https://github.com/ansible/ansible/issues/17495
- name: Install docker-py 1.9.0 to fix Ansible issue 17495
  pip:
    name: docker-py
    version: 1.9.0
    state: present
  when:
    - ansible_version is defined
    - ansible_version.full is version_compare('2.2.0.0', '<')

- name: Uninstall docker-py
  pip:
    name: docker-py
    state: absent
  when: (ansible_version is not defined) or
    (ansible_version is defined and ansible_version.full is version_compare('2.2.0.0', '>='))


- name: Install docker python lib
  pip:
    name: docker
    state: present
  when: (ansible_version is not defined) or
    (ansible_version is defined and ansible_version.full is version_compare('2.2.0.0', '>='))
