---

# Place to get apt repository key
apt_key_url: https://apt.dockerproject.org/gpg
# apt repository key signature
apt_key_sig: 2C52609D
# Name of the apt repository for docker
apt_repository: deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower|default('ubuntu') }}-{{ ansible_distribution_release|default('trusty') }} main
# Docker package Name
docker_package: docker-engine

# The following help expose a docker port or to add additional options when
# running docker daemon.  The default is to not use any special options.
#docker_opts: >
#  -H unix://
#  -H tcp://0.0.0.0:2375
#  --log-level=debug
docker_opts: ""
docker_tmpdir: ""

docker_config_file: /etc/default/docker

# A user who is allowed to run docker without sudo
docker_user: vagrant

# This is the name that must be used, according to documentation
# https://docs.docker.com/installation/ubuntulinux/#create-a-docker-group
docker_group: docker
