--
# file: registry.yml
# Create docker and singularity service stacks with shared, persistent
# storage volumes via glustefs and minio
# via for automated container builds.
# Terraform created a host group and corresponding group_vars/<username>
# files for ci.
- hosts: registry
  roles:
    - minio
    - registry
    - sregistry
