---

# Looks up the `access_token_user_id` user personal access token
- name: Query gitlab db for personal access token
  shell: docker run -i --rm  -e "PGPASSWORD={{ gitlab_postgres_db_password }}" {{ gitlab_postgres_db_image }} psql -U{{ gitlab_postgres_db_user }} -p{{ gitlab_postgres_db_port }} -h{{ hostvars[groups['gitlab'][0]]['ansible_ssh_host'] }} {{ gitlab_postgres_db_name }} -c "select token from personal_access_tokens where user_id = {{ access_token_user_id }} and name = 'ansible'"
  args:
    chdir: "/home/{{ devops_linux_user }}/gitlab"
  register: psql_user_personal_access_token

- debug:
    msg: Response from gitlab db
    var: psql_user_personal_access_token

#- name: Verify personal access token was found
#  assert:
#    that:
#      - "psql_user_personal_access_token is success"
#      - "len(psql_user_personal_access_token.stdout_lines) == 3"
#    msg: "No personal access token found"

- name: Register root personal access token fact
  set_fact:
    gitlab_root_personal_access_token: "{{ psql_user_personal_access_token.stdout_lines[1] | trim }}"
  when: "len(psql_user_personal_access_token.stdout_lines) == 3"