#
---

- name: Create GitLab data, log, and cert folders on the host.
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ devops_linux_user }}"
    group: "{{ devops_linux_user }}"
    mode: 0700
    recurse: yes
  loop:
    - "{{ gitlab_cert_dir }}"
    - "{{ gitlab_data_dir }}"
    - "{{ gitlab_registry_data_dir }}"

- name: Create GitLab data, log, and cert folders on the host.
  become: yes
  become_user: root
  file:
    path: "{{ gitlab_log_dir }}"
    state: directory
    owner: "{{ devops_linux_user }}"
    group: "{{ devops_linux_user }}"
    mode: 0770
    recurse: yes

- name: Create self-signed certificate for Gitlab.
  command: openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_cert_dir }}/{{ gitlab_ssl_certificate_key | basename }} -out {{ gitlab_cert_dir }}/{{ gitlab_ssl_certificate | basename }} -extensions v3_ca
  args:
    creates: "{{ gitlab_cert_dir }}/{{ gitlab_ssl_certificate | basename }}"
  when: gitlab_create_self_signed_cert

- name: Create self-signed certificate for the Docker Registry
  command: openssl req -new -nodes -x509 -subj "{{ gitlab_registry_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_cert_dir }}/{{ gitlab_registry_ssl_certificate_key | basename }} -out {{ gitlab_cert_dir }}/{{ gitlab_registry_ssl_certificate | basename }} -extensions v3_ca
  args:
    creates: "{{ gitlab_cert_dir }}/{{ gitlab_registry_ssl_certificate | basename }}"
  when: gitlab_deploy_registry

- name: Copy GitLab configuration files into place.
  template:
    src: "{{ item }}.j2"
    dest: "{{ gitlab_deploy_dir }}/{{ item }}"
    owner: "{{ devops_linux_user }}"
    group: "{{ devops_linux_user }}"
    mode: 0600
  loop:
    - docker-stack.yml
#    - gitlab.env
#    - postgres.env
#    - registry.env
#    - traefik.toml

- name: Stopping gitlab stack
  command: docker stack rm gitlab
  args:
    chdir: "{{ gitlab_deploy_dir }}"
  ignore_errors: true

- name: Ensuring Swarm network is present
  docker_network:
    name: swarm-overlay
    state: present
    driver: overlay

- name: Restarting gitlab stack
  command: docker stack deploy -c docker-stack.yml gitlab
  args:
    chdir: "{{ gitlab_deploy_dir }}"

- name: Waiting for Gitlab container to come online
  wait_for:
    host: "{{ gitlab_host | default(hostvars[groups['worker_node'][0]]['ansible_ssh_host']) }}"
    port: 30180

#- name: Resetting root user personal access token
#  import_tasks: set-user-personal-access-token.yml
#  vars:
#    access_token_user_id: 1