---

#
# Postgres database connectivity info. The DB will be bootstrapped at startup
# and stored in a docker volume on the host. Standard DB backups should apply.
#

# If a externally hosted postgresql server is used, set to falseg: true
# Postgres docker image to use
gitlab_postgres_db_image: sameersbn/postgresql:9.5-3
# Hostname of the database. For container deployment, this is always postgres
gitlab_postgres_db_host: postgresql
# Port of the database. For container deployment, this is always 5432 and will not
# only be available to the gitlab server
gitlab_postgres_db_port: 5432
# Database username
gitlab_postgres_db_user: gitlab
# Database password
gitlab_postgres_db_password: password
# Database name
gitlab_postgres_db_name: gitlabhq_production
# Database extension specific to gitlab needs
gitlab_postgres_db_extension: pg_trgm


# Hostname or ip of the gitlab instance
gitlab_host: "{{ hostvars[groups['gitlab'][0]]['ansible_ssh_host'] }}"

# Gitlab user id for whome to grant admin access. defaults to the root user
gitlab_admin_users_usernames: ""

# Set to false if revoking admin instead of granting. This applies to all
# users specified in `gitlab_admin_users_usernames`
gitlab_admin_user_revoke_privileges: false